// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddCardCreatedCode is the HTTP code returned for type AddCardCreated
const AddCardCreatedCode int = 201

/*
AddCardCreated card created

swagger:response addCardCreated
*/
type AddCardCreated struct {
}

// NewAddCardCreated creates AddCardCreated with default headers values
func NewAddCardCreated() *AddCardCreated {

	return &AddCardCreated{}
}

// WriteResponse to the client
func (o *AddCardCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddCardBadRequestCode is the HTTP code returned for type AddCardBadRequest
const AddCardBadRequestCode int = 400

/*
AddCardBadRequest invalid input, object invalid

swagger:response addCardBadRequest
*/
type AddCardBadRequest struct {
}

// NewAddCardBadRequest creates AddCardBadRequest with default headers values
func NewAddCardBadRequest() *AddCardBadRequest {

	return &AddCardBadRequest{}
}

// WriteResponse to the client
func (o *AddCardBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddCardConflictCode is the HTTP code returned for type AddCardConflict
const AddCardConflictCode int = 409

/*
AddCardConflict conflict - card already exists

swagger:response addCardConflict
*/
type AddCardConflict struct {
}

// NewAddCardConflict creates AddCardConflict with default headers values
func NewAddCardConflict() *AddCardConflict {

	return &AddCardConflict{}
}

// WriteResponse to the client
func (o *AddCardConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
