// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DelPersonNoContentCode is the HTTP code returned for type DelPersonNoContent
const DelPersonNoContentCode int = 204

/*
DelPersonNoContent person deleted

swagger:response delPersonNoContent
*/
type DelPersonNoContent struct {
}

// NewDelPersonNoContent creates DelPersonNoContent with default headers values
func NewDelPersonNoContent() *DelPersonNoContent {

	return &DelPersonNoContent{}
}

// WriteResponse to the client
func (o *DelPersonNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DelPersonBadRequestCode is the HTTP code returned for type DelPersonBadRequest
const DelPersonBadRequestCode int = 400

/*
DelPersonBadRequest invalid input, object invalid

swagger:response delPersonBadRequest
*/
type DelPersonBadRequest struct {
}

// NewDelPersonBadRequest creates DelPersonBadRequest with default headers values
func NewDelPersonBadRequest() *DelPersonBadRequest {

	return &DelPersonBadRequest{}
}

// WriteResponse to the client
func (o *DelPersonBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DelPersonNotFoundCode is the HTTP code returned for type DelPersonNotFound
const DelPersonNotFoundCode int = 404

/*
DelPersonNotFound person not exists

swagger:response delPersonNotFound
*/
type DelPersonNotFound struct {
}

// NewDelPersonNotFound creates DelPersonNotFound with default headers values
func NewDelPersonNotFound() *DelPersonNotFound {

	return &DelPersonNotFound{}
}

// WriteResponse to the client
func (o *DelPersonNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DelPersonConflictCode is the HTTP code returned for type DelPersonConflict
const DelPersonConflictCode int = 409

/*
DelPersonConflict conflict - can't delete person

swagger:response delPersonConflict
*/
type DelPersonConflict struct {
}

// NewDelPersonConflict creates DelPersonConflict with default headers values
func NewDelPersonConflict() *DelPersonConflict {

	return &DelPersonConflict{}
}

// WriteResponse to the client
func (o *DelPersonConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
