// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DelBankHandlerFunc turns a function with the right signature into a del bank handler
type DelBankHandlerFunc func(DelBankParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DelBankHandlerFunc) Handle(params DelBankParams) middleware.Responder {
	return fn(params)
}

// DelBankHandler interface for that can handle valid del bank params
type DelBankHandler interface {
	Handle(DelBankParams) middleware.Responder
}

// NewDelBank creates a new http.Handler for the del bank operation
func NewDelBank(ctx *middleware.Context, handler DelBankHandler) *DelBank {
	return &DelBank{Context: ctx, Handler: handler}
}

/*
	DelBank swagger:route DELETE /banks/{inn} admins delBank

remove bank by bic

Remove bank by bic
*/
type DelBank struct {
	Context *middleware.Context
	Handler DelBankHandler
}

func (o *DelBank) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDelBankParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
