// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DelPersonHandlerFunc turns a function with the right signature into a del person handler
type DelPersonHandlerFunc func(DelPersonParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DelPersonHandlerFunc) Handle(params DelPersonParams) middleware.Responder {
	return fn(params)
}

// DelPersonHandler interface for that can handle valid del person params
type DelPersonHandler interface {
	Handle(DelPersonParams) middleware.Responder
}

// NewDelPerson creates a new http.Handler for the del person operation
func NewDelPerson(ctx *middleware.Context, handler DelPersonHandler) *DelPerson {
	return &DelPerson{Context: ctx, Handler: handler}
}

/*
	DelPerson swagger:route DELETE /persons/{inn} admins delPerson

remove person by inn

Remove person by inn
*/
type DelPerson struct {
	Context *middleware.Context
	Handler DelPersonHandler
}

func (o *DelPerson) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDelPersonParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
