// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DelСardHandlerFunc turns a function with the right signature into a del сard handler
type DelСardHandlerFunc func(DelСardParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DelСardHandlerFunc) Handle(params DelСardParams) middleware.Responder {
	return fn(params)
}

// DelСardHandler interface for that can handle valid del сard params
type DelСardHandler interface {
	Handle(DelСardParams) middleware.Responder
}

// NewDelСard creates a new http.Handler for the del сard operation
func NewDelСard(ctx *middleware.Context, handler DelСardHandler) *DelСard {
	return &DelСard{Context: ctx, Handler: handler}
}

/*
	DelСard swagger:route DELETE /cards/{inn} admins delСard

remove an card item

Remove an card from the system
*/
type DelСard struct {
	Context *middleware.Context
	Handler DelСardHandler
}

func (o *DelСard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDelСardParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
