// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DelBankNoContentCode is the HTTP code returned for type DelBankNoContent
const DelBankNoContentCode int = 204

/*
DelBankNoContent bank deleted

swagger:response delBankNoContent
*/
type DelBankNoContent struct {
}

// NewDelBankNoContent creates DelBankNoContent with default headers values
func NewDelBankNoContent() *DelBankNoContent {

	return &DelBankNoContent{}
}

// WriteResponse to the client
func (o *DelBankNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DelBankBadRequestCode is the HTTP code returned for type DelBankBadRequest
const DelBankBadRequestCode int = 400

/*
DelBankBadRequest invalid input, object invalid

swagger:response delBankBadRequest
*/
type DelBankBadRequest struct {
}

// NewDelBankBadRequest creates DelBankBadRequest with default headers values
func NewDelBankBadRequest() *DelBankBadRequest {

	return &DelBankBadRequest{}
}

// WriteResponse to the client
func (o *DelBankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DelBankNotFoundCode is the HTTP code returned for type DelBankNotFound
const DelBankNotFoundCode int = 404

/*
DelBankNotFound bank not exists

swagger:response delBankNotFound
*/
type DelBankNotFound struct {
}

// NewDelBankNotFound creates DelBankNotFound with default headers values
func NewDelBankNotFound() *DelBankNotFound {

	return &DelBankNotFound{}
}

// WriteResponse to the client
func (o *DelBankNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DelBankConflictCode is the HTTP code returned for type DelBankConflict
const DelBankConflictCode int = 409

/*
DelBankConflict conflict - can't delete bank

swagger:response delBankConflict
*/
type DelBankConflict struct {
}

// NewDelBankConflict creates DelBankConflict with default headers values
func NewDelBankConflict() *DelBankConflict {

	return &DelBankConflict{}
}

// WriteResponse to the client
func (o *DelBankConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
