// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetCardOKCode is the HTTP code returned for type GetCardOK
const GetCardOKCode int = 200

/*
GetCardOK card found

swagger:response getCardOK
*/
type GetCardOK struct {
}

// NewGetCardOK creates GetCardOK with default headers values
func NewGetCardOK() *GetCardOK {

	return &GetCardOK{}
}

// WriteResponse to the client
func (o *GetCardOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetCardBadRequestCode is the HTTP code returned for type GetCardBadRequest
const GetCardBadRequestCode int = 400

/*
GetCardBadRequest invalid input, object invalid

swagger:response getCardBadRequest
*/
type GetCardBadRequest struct {
}

// NewGetCardBadRequest creates GetCardBadRequest with default headers values
func NewGetCardBadRequest() *GetCardBadRequest {

	return &GetCardBadRequest{}
}

// WriteResponse to the client
func (o *GetCardBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCardNotFoundCode is the HTTP code returned for type GetCardNotFound
const GetCardNotFoundCode int = 404

/*
GetCardNotFound card not exists

swagger:response getCardNotFound
*/
type GetCardNotFound struct {
}

// NewGetCardNotFound creates GetCardNotFound with default headers values
func NewGetCardNotFound() *GetCardNotFound {

	return &GetCardNotFound{}
}

// WriteResponse to the client
func (o *GetCardNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
