// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swagger_example/models"
)

// GetBanksOKCode is the HTTP code returned for type GetBanksOK
const GetBanksOKCode int = 200

/*
GetBanksOK search results matching criteria

swagger:response getBanksOK
*/
type GetBanksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Bank `json:"body,omitempty"`
}

// NewGetBanksOK creates GetBanksOK with default headers values
func NewGetBanksOK() *GetBanksOK {

	return &GetBanksOK{}
}

// WithPayload adds the payload to the get banks o k response
func (o *GetBanksOK) WithPayload(payload []*models.Bank) *GetBanksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get banks o k response
func (o *GetBanksOK) SetPayload(payload []*models.Bank) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBanksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Bank, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBanksBadRequestCode is the HTTP code returned for type GetBanksBadRequest
const GetBanksBadRequestCode int = 400

/*
GetBanksBadRequest bad input parameter

swagger:response getBanksBadRequest
*/
type GetBanksBadRequest struct {
}

// NewGetBanksBadRequest creates GetBanksBadRequest with default headers values
func NewGetBanksBadRequest() *GetBanksBadRequest {

	return &GetBanksBadRequest{}
}

// WriteResponse to the client
func (o *GetBanksBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
