// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPersonOKCode is the HTTP code returned for type GetPersonOK
const GetPersonOKCode int = 200

/*
GetPersonOK person found

swagger:response getPersonOK
*/
type GetPersonOK struct {
}

// NewGetPersonOK creates GetPersonOK with default headers values
func NewGetPersonOK() *GetPersonOK {

	return &GetPersonOK{}
}

// WriteResponse to the client
func (o *GetPersonOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetPersonBadRequestCode is the HTTP code returned for type GetPersonBadRequest
const GetPersonBadRequestCode int = 400

/*
GetPersonBadRequest invalid input, object invalid

swagger:response getPersonBadRequest
*/
type GetPersonBadRequest struct {
}

// NewGetPersonBadRequest creates GetPersonBadRequest with default headers values
func NewGetPersonBadRequest() *GetPersonBadRequest {

	return &GetPersonBadRequest{}
}

// WriteResponse to the client
func (o *GetPersonBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetPersonNotFoundCode is the HTTP code returned for type GetPersonNotFound
const GetPersonNotFoundCode int = 404

/*
GetPersonNotFound person not exists

swagger:response getPersonNotFound
*/
type GetPersonNotFound struct {
}

// NewGetPersonNotFound creates GetPersonNotFound with default headers values
func NewGetPersonNotFound() *GetPersonNotFound {

	return &GetPersonNotFound{}
}

// WriteResponse to the client
func (o *GetPersonNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
