// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetBankOKCode is the HTTP code returned for type GetBankOK
const GetBankOKCode int = 200

/*
GetBankOK bank found

swagger:response getBankOK
*/
type GetBankOK struct {
}

// NewGetBankOK creates GetBankOK with default headers values
func NewGetBankOK() *GetBankOK {

	return &GetBankOK{}
}

// WriteResponse to the client
func (o *GetBankOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetBankBadRequestCode is the HTTP code returned for type GetBankBadRequest
const GetBankBadRequestCode int = 400

/*
GetBankBadRequest invalid input, object invalid

swagger:response getBankBadRequest
*/
type GetBankBadRequest struct {
}

// NewGetBankBadRequest creates GetBankBadRequest with default headers values
func NewGetBankBadRequest() *GetBankBadRequest {

	return &GetBankBadRequest{}
}

// WriteResponse to the client
func (o *GetBankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetBankNotFoundCode is the HTTP code returned for type GetBankNotFound
const GetBankNotFoundCode int = 404

/*
GetBankNotFound bank not exists

swagger:response getBankNotFound
*/
type GetBankNotFound struct {
}

// NewGetBankNotFound creates GetBankNotFound with default headers values
func NewGetBankNotFound() *GetBankNotFound {

	return &GetBankNotFound{}
}

// WriteResponse to the client
func (o *GetBankNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
