// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// NewPersonHandlerFunc turns a function with the right signature into a new person handler
type NewPersonHandlerFunc func(NewPersonParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NewPersonHandlerFunc) Handle(params NewPersonParams) middleware.Responder {
	return fn(params)
}

// NewPersonHandler interface for that can handle valid new person params
type NewPersonHandler interface {
	Handle(NewPersonParams) middleware.Responder
}

// NewNewPerson creates a new http.Handler for the new person operation
func NewNewPerson(ctx *middleware.Context, handler NewPersonHandler) *NewPerson {
	return &NewPerson{Context: ctx, Handler: handler}
}

/*
	NewPerson swagger:route POST /persons admins newPerson

adds new person item

Adds new person to the system
*/
type NewPerson struct {
	Context *middleware.Context
	Handler NewPersonHandler
}

func (o *NewPerson) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNewPersonParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
