// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// NewBankCreatedCode is the HTTP code returned for type NewBankCreated
const NewBankCreatedCode int = 201

/*
NewBankCreated new bank created

swagger:response newBankCreated
*/
type NewBankCreated struct {
}

// NewNewBankCreated creates NewBankCreated with default headers values
func NewNewBankCreated() *NewBankCreated {

	return &NewBankCreated{}
}

// WriteResponse to the client
func (o *NewBankCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// NewBankBadRequestCode is the HTTP code returned for type NewBankBadRequest
const NewBankBadRequestCode int = 400

/*
NewBankBadRequest invalid input, object invalid

swagger:response newBankBadRequest
*/
type NewBankBadRequest struct {
}

// NewNewBankBadRequest creates NewBankBadRequest with default headers values
func NewNewBankBadRequest() *NewBankBadRequest {

	return &NewBankBadRequest{}
}

// WriteResponse to the client
func (o *NewBankBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// NewBankConflictCode is the HTTP code returned for type NewBankConflict
const NewBankConflictCode int = 409

/*
NewBankConflict conflict - bank already exists

swagger:response newBankConflict
*/
type NewBankConflict struct {
}

// NewNewBankConflict creates NewBankConflict with default headers values
func NewNewBankConflict() *NewBankConflict {

	return &NewBankConflict{}
}

// WriteResponse to the client
func (o *NewBankConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
