// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// NewPersonCreatedCode is the HTTP code returned for type NewPersonCreated
const NewPersonCreatedCode int = 201

/*
NewPersonCreated person created

swagger:response newPersonCreated
*/
type NewPersonCreated struct {
}

// NewNewPersonCreated creates NewPersonCreated with default headers values
func NewNewPersonCreated() *NewPersonCreated {

	return &NewPersonCreated{}
}

// WriteResponse to the client
func (o *NewPersonCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// NewPersonBadRequestCode is the HTTP code returned for type NewPersonBadRequest
const NewPersonBadRequestCode int = 400

/*
NewPersonBadRequest invalid input, object invalid

swagger:response newPersonBadRequest
*/
type NewPersonBadRequest struct {
}

// NewNewPersonBadRequest creates NewPersonBadRequest with default headers values
func NewNewPersonBadRequest() *NewPersonBadRequest {

	return &NewPersonBadRequest{}
}

// WriteResponse to the client
func (o *NewPersonBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// NewPersonConflictCode is the HTTP code returned for type NewPersonConflict
const NewPersonConflictCode int = 409

/*
NewPersonConflict conflict - person already exists

swagger:response newPersonConflict
*/
type NewPersonConflict struct {
}

// NewNewPersonConflict creates NewPersonConflict with default headers values
func NewNewPersonConflict() *NewPersonConflict {

	return &NewPersonConflict{}
}

// WriteResponse to the client
func (o *NewPersonConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
