// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// NewBankHandlerFunc turns a function with the right signature into a new bank handler
type NewBankHandlerFunc func(NewBankParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NewBankHandlerFunc) Handle(params NewBankParams) middleware.Responder {
	return fn(params)
}

// NewBankHandler interface for that can handle valid new bank params
type NewBankHandler interface {
	Handle(NewBankParams) middleware.Responder
}

// NewNewBank creates a new http.Handler for the new bank operation
func NewNewBank(ctx *middleware.Context, handler NewBankHandler) *NewBank {
	return &NewBank{Context: ctx, Handler: handler}
}

/*
	NewBank swagger:route POST /banks admins newBank

adds an bank item

Adds new bank to the system
*/
type NewBank struct {
	Context *middleware.Context
	Handler NewBankHandler
}

func (o *NewBank) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewNewBankParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
