// Code generated by go-swagger; DO NOT EDIT.

// Package restapi bcard_microservice_api
//
//	Sample OpenAPI2.0 spec for demo microservice bcard:
//	Check valid paycard (exist & not expiried)
//	CRUD Card, Person, Bank & check valid
//
//
//	Schemes:
//	  http
//	Host: virtserver.swaggerhub.com
//	BasePath: /go9130416421/bcard/1.0.0
//	Version: 1.0.0
//	License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: <nba.linx@gmail.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
